openapi: '3.0.3'
info:
  title: FOX API
  version: '1.0'

servers:
  - url: http://localhost/fox-api/v1

components:
  schemas:
    product_data:
      type: object
      properties:
        id:
          description: 'Product ID'
          type: integer
          minimum: 0
          exclusiveMinimum: true
        name:
          description: 'Product name'
          type: string
          maxLength: 255
        price:
          description: 'Price per piece'
          type: number
          format: float
          minimum: 0
        stock:
          description: 'Number of pieces in stock'
          type: integer
          minimum: 0
        created_at:
          description: 'Product creation date'
          type: string
          format: date-time
        updated_at:
          description: 'Product last modified date'
          type: string
          format: date-time
          nullable: true
        deleted:
          description: 'Flag indicating deleted item'
          type: boolean
    product_input:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 255
        price:
          type: number
          format: float
          minimum: 0
          default: 0
        stock:
          type: integer
          minimum: 0
          default: 0
  responses:
    error:
      description: 'Error'
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              error:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
    status:
      description: 'Status'
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string

paths:
  /:
    get:
      responses:
        '200':
          description: 'TEST'

  /product:
    get:
      description: 'Get product by ID'
      parameters:
        - name: 'id'
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Product found'
          $ref: "#/components/responses/status"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product_data"
        '400':
          description: 'Product ID is missing'
          $ref: "#/components/responses/error"
        '404':
          description: 'Product not found'
          $ref: "#/components/responses/error"
    post:
      description: 'Create product'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/product_input"
      responses:
        '200':
          description: 'Successfully created a new product'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product_data"
        '400':
          $ref: "#/components/responses/error"
    patch:
      description: 'Update product'
      parameters:
        - name: 'id'
          in: query
          required: false
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/product_input"
      responses:
        '200':
          description: 'Successfully created a new product'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product_data"
        '400':
          $ref: "#/components/responses/error"
    put:
      description: 'Update product if exists, otherwise Create new product'
      parameters:
        - name: 'id'
          in: query
          required: false
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/product_input"
      responses:
        '200':
          description: 'Successfully created a new product'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product_data"
        '400':
          $ref: "#/components/responses/error"
    delete:
      description: 'Delete product by ID'
      parameters:
        - name: 'id'
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Product deleted'
          $ref: "#/components/responses/status"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product_data"
        '400':
          description: 'Product ID is missing'
          $ref: "#/components/responses/error"
        '404':
          description: 'Product not found'
          $ref: "#/components/responses/error"

  /products:
    get:
      description: 'Get product list according to limit and offset with filtering (optional)'
      parameters:
        - name: 'limit'
          in: query
          description: 'Limits the number of items on a page'
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: 'offset'
          in: query
          description: 'Specifies the page number of the items to be displayed'
          schema:
            type: integer
            default: 0
        - name: 'name'
          in: query
          description: 'Search for part of name'
          schema:
            type: string
            minLength: 3
            maxLength: 255
        - name: 'minPrice'
          in: query
          description: 'Minimal price'
          schema:
            type: number
            format: float
            minimum: 0
        - name: 'maxPrice'
          in: query
          description: 'Maximal price'
          schema:
            type: number
            format: float
        - name: 'minStock'
          in: query
          description: 'Minimal stock'
          schema:
            type: integer
            minimum: 0
        - name: 'maxStock'
          in: query
          description: 'Maximal stock'
          schema:
            type: integer
      responses:
        '200':
          description: 'List of products'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/product_data"
        '404':
          description: 'No products are found'
          $ref: "#/components/responses/error"

